create TABLE interactions_clients_sites_detail
AS
SELECT DISTINCT interaction_id, INTERACTIONS.SITE_ID, INTERACTIONS.CLIENT_ID, CLIENTS.CLIENT_ZIPCODE_TRUNC client_zip, SITEADDRESSUS_SITEADDRESSUS_LATITUDE SITE_LATITUDE,SITEADDRESSUS_SITEADDRESSUS_LONGITUDE SITE_LONGITUDE,SITEADDRESSUS_SITEADDRESSUS_ZIP SITE_ZIP
FROM INTERACTIONS
LEFT JOIN CLIENTS
ON INTERACTIONS.CLIENT_ID = CLIENTS.CLIENT_ID
LEFT JOIN SITES
ON SITES.SITE_ID = NULLIF(INTERACTIONS.SITE_ID,'None');
